apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modialogin
  namespace: {{ namespace }}
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modialogin/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modialogin/internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app-{{ namespace }}.adeo.no/modialogin
#    - https://modialogin-{{ namespace }}.dev.adeo.no/modialogin
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/appdynamics
      - kvPath: /kv/preprod/fss/modialogin/{{ namespace }}
        mountPath: /var/run/secrets/nais.io/vault