apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modialogin-{{ q_env }}
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modialogin/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modialogin/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modialogin/internal/metrics
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app-{{ q_env }}.adeo.no/modialogin
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/appdynamics
      - kvPath: /kv/preprod/fss/modialogin-{{ q_env }}/personoversikt
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: APP_NAME
      value: "modialogin"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: AUTH_TOKEN_RESOLVER
      value: "modia_ID_token"
    - name: REFRESH_TOKEN_RESOLVER
      value: "modia_refresh_token"