name: Frontend app

on:
  push:
    paths-ignore:
      - '.github/workflows/login-app-workflow.yml'
      - 'oidc-stub/**'
      - 'login-app/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'docker-compose.yml'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/frontend:${{ github.sha }}
  BETA_IMAGE: docker.pkg.github.com/${{ github.repository }}/frontend:${{ github.sha }}-beta
  CI: true
  TZ: Europe/Oslo
jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup test-containers
        run: docker-compose up --build -d
      - name: Test
        run: node test/test.js
      - name: Teardown test-container
        run: docker-compose down
     -  name: Publish beta-image
        if: github.ref == 'refs/heads/dev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${BETA_IMAGE} nginx
          docker push ${IMAGE}
      - name: Publish image
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${IMAGE} nginx
          docker push ${IMAGE}