name: Frontend app

on:
  push:
    paths-ignore:
      - '.nais/**'
      - '**.md'
      - '.editorconfig'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'docker-compose.yml'

concurrency:
  group: frontend-app-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  TZ: Europe/Oslo
jobs:
  build:
    name: Test, build and publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Build
        run:  ./gradlew build
      - name: Setup test-containers
        run: make integrationtest-setup
      - name: Test
        run: |
          make integrationtest-test-redis
          make integrationtest-test-postgresql
      - name: Teardown test-containers
        run: make integrationtest-teardown
      - name: Publish beta-image
        if: github.ref == 'refs/heads/dev'
        uses: nais/docker-build-push@v0
        id: docker-build-push-beta
        with:
          team: personoversikt
          tag: ${{ github.sha }}-beta
          image_suffix: 'beta'
          docker_context: frontend-app
          dockerfile: 'frontend-app/Dockerfile'
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Publish image
        if: github.ref == 'refs/heads/master'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: personoversikt
          tag: ${{ github.sha }}
          docker_context: frontend-app
          dockerfile: 'frontend-app/Dockerfile'
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}